<<<<<<<<<<<<<<<<<<<..................................*................*========================================*.................*......................................>>>>>>>>>>>>>>>>>>>

*                                                          >> ANALYTICAL PYTHON <<                                                          *

<<<<<<<<<<<<<<<<<<<..................................*................*========================================*.................*......................................>>>>>>>>>>>>>>>>>>>

In [14]:
! pip install numpy

In [479]:
import numpy as np

In [481]:
np.__version__  # for find verision of numpy

'1.26.4'

In [483]:
a=[2,3,6,9,4]
b=[1,2,3,4,5]
ma=np.array(a) #to create a array
ml=np.array([3,5,6,8,1]) #to create array in single line code
print(ma)
print(ml)

[2 3 6 9 4]
[3 5 6 8 1]


|||.................................................................................................................................................................................................................................................................................................................................................................|||

||>> AGGREGATED FUNCTIONS 

In [727]:
np.mean(ma) #for getting mean value of array

4.8

In [729]:
np.mean(ml) #for getting mean value of array


4.6

In [731]:
np.median(ma) #get median value of array

4.0

In [733]:
np.median(ml) #get median value of array

5.0

In [735]:
np.std(ma) #to find array's standard deviation 

2.4819347291981715

In [737]:
np.std(ml) #to find array's standard deviation 

2.4166091947189146

In [739]:
np.sum((ma,ml),dtype=int) # for addition of 2 array's total sum values.

47

In [741]:
np.sum(ma) #get addition of all value of a array

24

In [743]:
np.sum(ml) #get addition of all value of a array

23

In [745]:
np.min(ma) # get minimum (smallest) value from array

2

In [747]:
np.min(ml) # get minimum (smallest) value from array

1

In [749]:
np.max(ma) # get maximum (biggest) value from array

9

In [751]:
np.max(ml) # get maximum (biggest) value from array

8

In [753]:
d1=np.array([1,2,3]) # d1.cumsum(axis=1) not work in 1D 


In [755]:
d2=np.array([[1,2,3],[4,5,6],[7,8,9]]) # cumulative sum of the elements in a dimensional array (2D)
print(d2)
d2.cumsum(axis=1)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


array([[ 1,  3,  6],
       [ 4,  9, 15],
       [ 7, 15, 24]])

In [757]:
d3=np.array([[[1,2,3],[4,5,6],[7,8,9]]]) # cumulative sum of the elements in a dimensional array (3D)
print(d3)
d3.cumsum(axis=2)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]


array([[[ 1,  3,  6],
        [ 4,  9, 15],
        [ 7, 15, 24]]])

In [759]:
np.corrcoef(d1) #Correlation coefficient

1.0

In [761]:
np.corrcoef(d2) #Correlation coefficient more than 2 dimensions can't run

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

|||.................................................................................................................................................................................................................................................................................................................................................................|||

||>> ARITHMETIC OPERATIONS 

In [768]:
np.subtract (10,5)  #subtract 2 values (max 2 number can do)

5

In [770]:
np.subtract (ma,ml) # For subtract array's values each other

array([-1, -2,  0,  1,  3])

In [772]:
# for subtract between sum of 2 array's
a1=np.sum(ma) #sum value is : 24
a2=np.sum(ml) #sum value is : 23
print(np.subtract (a1,a2)) #24-23=....?

1


In [774]:
np.add(ma,ml) # for addition 2 array's values each other NB: not for total sum. 

array([ 5,  8, 12, 17,  5])

In [776]:
np.add(25,20) #addition 2 numbers

45

In [778]:
np.multiply(2,5) #for multiplying 2 values 

10

In [780]:
np.multiply(ma,ml) # multiplying 2 array's elements each other. 

array([ 6, 15, 36, 72,  4])

In [782]:
np.divide(20,4) # for divide 2 values 

5.0

In [784]:
np.divide(ma,ml) #divide 2 array's elements each other

array([0.66666667, 0.6       , 1.        , 1.125     , 4.        ])

In [786]:
np.exp(ma) #get exponential of all values of a array

array([7.38905610e+00, 2.00855369e+01, 4.03428793e+02, 8.10308393e+03,
       5.45981500e+01])

In [788]:
np.exp(ml) #get exponential of all values of a array

array([2.00855369e+01, 1.48413159e+02, 4.03428793e+02, 2.98095799e+03,
       2.71828183e+00])

In [790]:
np.sin(ma) #get sin of all values of a array

array([ 0.90929743,  0.14112001, -0.2794155 ,  0.41211849, -0.7568025 ])

In [792]:
np.sin(ml) #get sin of all values of a array

array([ 0.14112001, -0.95892427, -0.2794155 ,  0.98935825,  0.84147098])

In [794]:
np.sqrt(ma) # get square root of all values of a array

array([1.41421356, 1.73205081, 2.44948974, 3.        , 2.        ])

In [796]:
np.sqrt(ml) # get square root of all values of a array

array([1.73205081, 2.23606798, 2.44948974, 2.82842712, 1.        ])

In [798]:
np.log(ma) #Element-wise natural logarithm from array

array([0.69314718, 1.09861229, 1.79175947, 2.19722458, 1.38629436])

In [800]:
np.log(ml) #Element-wise natural logarithm from array

array([1.09861229, 1.60943791, 1.79175947, 2.07944154, 0.        ])

In [802]:
z1=np.sum(ma)
z2=np.sum(ml)
z3=np.multiply(z1,z2) #for multiply sum of array's values.
print(z3)

552


In [804]:
a3=np.sum((ma,ml),dtype=int) #sum value is : 24+25=49
a4=np.mean(ma) # value =4.8
a5=np.mean(ml) # value =4.6
np.multiply(a4,a5) #for multiply average of array's values.4.6*4.8=.....?

22.08

|||.................................................................................................................................................................................................................................................................................................................................................................|||

||>> COMPARISON 

In [811]:
ma==ml #element-wise comparison 

array([False, False,  True, False, False])

In [813]:
ma<ml #element-wise comparison 

array([ True,  True, False, False, False])

In [815]:
np.array_equal(ma,ml) #Array-wise comparison

False

|||.................................................................................................................................................................................................................................................................................................................................................................|||

||>> DATA TYPE

In [820]:
np.int64 #Signed 64-bit integer types

numpy.int64

In [822]:
np.float32 #Standard double-precision floating point

numpy.float32

In [824]:
np.object_ #Python object type

numpy.object_

In [826]:
 np.string_ #Fixed-length string type

numpy.bytes_

In [828]:
np.unicode_ #Fixed-length unicode type

numpy.str_

|||.................................................................................................................................................................................................................................................................................................................................................................|||

 ||>> NUMPY ARRAYS DIMENSIONS 

In [836]:
d1=np.array([1,2,3])                      #1D  1 dimensional array
d2=np.array([[1,2,3],[4,5,6],[7,8,9]])    #2D  2 dimensional array
d3=np.array([[[1,2,3],[4,5,6],[7,8,9]]])  #3D  3 dimensional array
print(d1)
print()
print(d2)
print()
print(d3)

[1 2 3]

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]


|||.................................................................................................................................................................................................................................................................................................................................................................|||

||>> SAVING AND LOADING ON DISK

In [858]:
np.save("MY ARRAY",a)

In [860]:
np.savez("ARRAY.NPZ",a,b)

In [862]:
np.load("MY ARRAY.NPY")

array([10, 15, 20, 25, 30])

|||.................................................................................................................................................................................................................................................................................................................................................................|||

||>> INSPECTING ARRAY

In [878]:
g4=np.arange(20) #add a range off numbers to array multiply with "1"
print(g4)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [880]:
g5=np.arange(10,31)#add specific (start to end) values to array multiply with "1"
g5

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30])

In [882]:
g6=np.arange(0,50,5)#add values to array (start,end,action)
g6

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45])

In [884]:
g6.size # to check how much values inside off that specific array 

10

In [886]:
g6.shape # to check shape of array

(10,)

In [888]:
g6.dtype # to check type of array

dtype('int32')

In [890]:
g6.ndim # to check dimensions 

1

In [892]:
d3.ndim # to check dimensions 

3

In [894]:
k1=np.array([1,2,3,4,5,6,7,8],ndmin=2) # for setting diamentions same time of array creation
k1.shape

(1, 8)

In [896]:
k1=k1.reshape(2,4)
k1.shape

(2, 4)

In [898]:
len(k1) #Length of array

2

In [900]:
ml.dtype.name #Name of data type

'int32'

In [902]:
ma.astype(int)

array([2, 3, 6, 9, 4])

|||.................................................................................................................................................................................................................................................................................................................................................................|||

||>> INITIAL PLACEHOLDERS

In [910]:
k2=np.zeros(5,dtype=int) #Create an array of zeros 1D
print(k2)

[0 0 0 0 0]


In [912]:
k2=np.zeros((5,4),dtype=int) #Create an array of zeros 2D
print(k2)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [914]:
k3=np.zeros((2,3,4),dtype=int) #Create an array of zeros 3D
print(k3)

[[[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]

 [[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]]


In [916]:
k4=np.ones(5,dtype=int) #Create an array of ones 1D
print(k4)

[1 1 1 1 1]


In [918]:
k4=np.ones((4,3),dtype=int) #Create an array of ones 2D
print(k4)

[[1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]]


In [920]:
k4=np.ones((2,4,4),dtype=int) #Create an array of ones 3D
print(k4)
print(k4.shape)

[[[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]]
(2, 4, 4)


In [922]:
em=np.empty(6,dtype=int) #Create an empty array 6 row only
print(em)

[         0 1072693248          0 1072693248          0 1072693248]


In [924]:
em=np.empty((6,4),dtype=int) #Create an empty array 4 row 6 column 
print(em)

[[ 908599752        569         58          0]
 [         0          0          0          0]
 [         0         57 1852990827  808348773]
 [ 811938661  761409634  862021175  929444909]
 [ 943205733  908933429 1647325745 1633837369]
 [ 778462050 1667594341 1600484469 1970496882]]


In [926]:
i=np.eye(3,dtype=int) #Create a 2X2 identity matrix
print(i)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [928]:
np.linspace(10,20,30) #Create an array of evenly spaced values (number of samples)

array([10.        , 10.34482759, 10.68965517, 11.03448276, 11.37931034,
       11.72413793, 12.06896552, 12.4137931 , 12.75862069, 13.10344828,
       13.44827586, 13.79310345, 14.13793103, 14.48275862, 14.82758621,
       15.17241379, 15.51724138, 15.86206897, 16.20689655, 16.55172414,
       16.89655172, 17.24137931, 17.5862069 , 17.93103448, 18.27586207,
       18.62068966, 18.96551724, 19.31034483, 19.65517241, 20.        ])

In [930]:
np.linspace(0,1,10) #Create an array of evenly spaced values

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [932]:
np.linspace(1234,9898,20) #Create an array of evenly spaced values

array([1234., 1690., 2146., 2602., 3058., 3514., 3970., 4426., 4882.,
       5338., 5794., 6250., 6706., 7162., 7618., 8074., 8530., 8986.,
       9442., 9898.])

In [934]:
np.random.random((10)) # ramdom numbers will store to array 1D

array([0.87253231, 0.71059901, 0.12374819, 0.94155659, 0.7527445 ,
       0.1937787 , 0.17486409, 0.41559631, 0.42590327, 0.72365911])

In [936]:
np.random.random((3,5)) # ramdom numbers will store to array 2D

array([[0.93853208, 0.62177311, 0.34639653, 0.83188142, 0.57666627],
       [0.10987465, 0.38336395, 0.46226882, 0.30110849, 0.0603295 ],
       [0.4093493 , 0.88712608, 0.67548326, 0.91167518, 0.66951122]])

In [938]:
np.random.random((2,3,5)) # ramdom numbers will store to array  3D

array([[[7.66881226e-04, 3.15336888e-01, 3.03717453e-01, 7.84968409e-01,
         3.80531247e-01],
        [1.56666679e-02, 8.46268930e-01, 4.62743535e-01, 5.53737671e-01,
         9.30951097e-02],
        [4.48728509e-01, 2.40108297e-01, 6.42662519e-01, 6.21354928e-01,
         4.78438625e-01]],

       [[6.69670165e-01, 2.70016515e-01, 1.13977614e-01, 9.22675797e-01,
         2.77318028e-01],
        [6.50280878e-02, 6.33690903e-01, 4.26751300e-01, 2.93038572e-01,
         8.12237408e-01],
        [4.96772484e-01, 5.10032530e-01, 5.77770325e-01, 9.28322030e-01,
         1.48066375e-01]]])

In [940]:
np.random.rand(10) #to assign random and egually different numbers between 0 to 1  1D

array([0.36952053, 0.98043802, 0.53607893, 0.79713671, 0.40282577,
       0.27462187, 0.49642179, 0.24156725, 0.17175709, 0.96949049])

In [942]:
np.random.rand(3,5) #to assign random and egually different numbers between 0 to 2D

array([[0.55551798, 0.39371826, 0.61504449, 0.38208315, 0.7103881 ],
       [0.6461738 , 0.56816633, 0.3680844 , 0.57006434, 0.08993018],
       [0.21195896, 0.81120792, 0.95017431, 0.61223365, 0.65041781]])

In [944]:
np.random.rand(2,3,5) #to assign random and egually different numbers between 0 to 3D

array([[[0.08084762, 0.50171117, 0.61621199, 0.23388458, 0.37189674],
        [0.32266584, 0.77424798, 0.90641132, 0.4924199 , 0.25920714],
        [0.31018403, 0.54953692, 0.10721654, 0.43692649, 0.15251564]],

       [[0.16456555, 0.01684222, 0.32981043, 0.89820391, 0.44606016],
        [0.65369859, 0.93265219, 0.59296075, 0.47414189, 0.27945587],
        [0.46417934, 0.20788359, 0.93917331, 0.05603012, 0.06078324]]])

In [946]:
np.random.randn(10) #to assign random and different numbers between -1 to 1

array([ 2.30365382,  0.28856177,  1.08175707, -0.81123905, -1.97140013,
        0.64281374, -0.03053713, -0.0687615 ,  1.02025494,  0.65677654])

In [948]:
np.random.randn(2,5) #to assign random and different numbers between -1 to 1

array([[-1.35885723,  0.3533247 , -0.98488109,  1.02540378, -0.31017244],
       [ 0.34869965,  0.40537519, -1.52076065, -2.13091444, -0.18875607]])

In [950]:
np.random.randn(3,2,5) #to assign random and different numbers between -1 to 1 

array([[[-0.65787053,  0.2383376 ,  0.1304912 ,  0.12380902,
         -0.0165755 ],
        [ 1.0641025 ,  1.32927055,  1.05974797, -1.9264269 ,
          0.98083413]],

       [[ 1.08584095,  0.33420578,  1.5379859 , -0.78399968,
         -2.32991082],
        [-0.92783182,  1.62793921, -1.07128033, -0.23307412,
         -0.22422668]],

       [[-0.69445169,  1.065055  , -0.60859245, -0.71911729,
         -0.06392071],
        [-0.63128835,  0.19438675,  0.86996121,  0.90050757,
          0.48426066]]])

In [952]:
h1=np.full((2,2),7) #Create a constant array
print(h1)

[[7 7]
 [7 7]]


|||.................................................................................................................................................................................................................................................................................................................................................................|||

In [976]:
a=[10,15,20,25,30]
a*3

[10, 15, 20, 25, 30, 10, 15, 20, 25, 30, 10, 15, 20, 25, 30]

In [978]:
a1=np.array(a)
print(a1)


[10 15 20 25 30]


In [980]:
a1*3

array([30, 45, 60, 75, 90])

In [982]:
test=np.array([10,20,30,40,50,60,70,80])
print(test)

[10 20 30 40 50 60 70 80]


In [984]:
test[test>40]

array([50, 60, 70, 80])

In [986]:
test[test>=40]

array([40, 50, 60, 70, 80])

In [988]:
test[test<=50]

array([10, 20, 30, 40, 50])

In [990]:
np.log(5)

1.6094379124341003

In [992]:
np.nan

nan